---
- hosts: all
  become: yes
  #ignore_errors: yes
  gather_facts: no
  vars_files:
     - vars.yml
  tasks:
    - name: Copy config file
      template:
        dest: /tmp/apache.conf
        src: /home/ec2-user/ansible-dev/apache.j2